apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: note-app
  namespace: notes-app-ns
spec:
  type: ClusterIP
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

